app = "jobswipe-grafana"
primary_region = "iad"

[build]
  image = "grafana/grafana:latest"

[env]
GF_SECURITY_ADMIN_PASSWORD = "${GRAFANA_ADMIN}"
GF_USERS_ALLOW_SIGN_UP = "false"
GF_INSTALL_PLUGINS = "grafana-piechart-panel"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[processes]
app = "grafana-server --config=/etc/grafana/grafana.ini --homepath=/usr/share/grafana"

[[mounts]]
source = "grafana_data"
destination = "/var/lib/grafana"